config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/about', to: 'static_pages#about'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts
  resources :follows, only: [:create, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  resources :account_activations, only: [:edit]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def index
    @post = current_user.favorite_post.paginate(page: params[:page], per_page: 10)
  end

  def create
    # save just before page location
    set_just_before_location
    
    # favorite
    current_user.favorite(Post.find_by(id: favorite_params))

    # go back to just before page location
    redirect_to get_just_before_location
  end

  def destroy
    # save just before page location
    set_just_before_location

    # unfavorite
    current_user.unfavorite(Post.find_by(id: favorite_params))
    
    # go back to just before page location
    redirect_to get_just_before_location
  end

  private
    def favorite_params
      params.require(:post_id)
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite_button.html.slim
- if logged_in?
  - if current_user.favorites?(post)
    = form_for(:favorites, url: favorite_path, method: :delete, remote: true) do |f|
      = hidden_field_tag :post_id, post.id
      = f.submit "お気に入り解除", class: 'btn btn-outline-primary btn-sm', id: "post_#{post.id}_unfavorite_button"
  - else  
    = form_for(:favorites, url: favorites_path, remote: true) do |f|
      = hidden_field_tag :post_id, post.id
      = f.submit "お気に入り登録", class: 'btn btn-outline-primary btn-sm', id: "post_#{post.id}_favorite_button"
- else
  br

app/views/favorites/index.html.slim
.container-fluid
  .row.justify-content-center
    h3.mt-3 お気に入りリスト
br

= render "posts/post_list", post: @post