config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/about', to: 'static_pages#about'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts
  resources :follows, only: [:create, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  resources :account_activations, only: [:edit]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/user.rb
class User < ApplicationRecord
  has_many :post, dependent: :destroy
  has_many :active_follow, class_name: "FollowUser",
              foreign_key: "following_user_id",
              dependent: :destroy
  has_many :passive_follow, class_name: "FollowUser",
              foreign_key: "target_user_id",
              dependent: :destroy
  has_many :target_user, through: :active_follow
  has_many :following_user, through: :passive_follow
  has_many :favorite, dependent: :destroy
  has_many :favorite_post, through: :favorite, source: :post

  attr_accessor :remember_token, :activation_token
  validates :name, presence: true, length: {maximum: 20}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: {maximum: 20}, allow_nil: true

  before_create :prepare_activate
  before_save :downcase_email
  
  mount_uploader :image_key, ImageUploader

  # function
  #   ・function to save remember token for cookie
  # used
  #   ・save login information in cookie
  def remember_in_db
    self.remember_token = create_token
    update_attribute(:remember_digest, digest(self.remember_token))
  end

  # function
  #   ・function to delete remember token for cookie
  # used
  #   ・logout
  def forget_in_db
    update_attribute(:remember_digest, nil)
  end

  # function
  #   ・function to authenticated by cookie
  # used
  #    。login by cookie
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    return false if attribute == :activation and Time.zone.now > self.activated_at.since(2.hours)
    BCrypt::Password.new(digest).is_password?(token)
  end

  # function
  #   ・function to authenticate new user
  # used
  #    ・create new user
  def prepare_activate
    if !self.activated?
      self.activation_token = create_token
      self.activation_digest = digest(self.activation_token)
      self.activated_at = Time.zone.now
    end
  end

  # function
  #   ・function to authenticate new user
  # used
  #    ・create new user
  def activate
    update_attribute(:activated, true)
    update_attribute(:activation_digest, nil)
    update_attribute(:activated_at, Time.zone.now)
  end

  # function
  #   ・function to follow
  # used
  #    ・update follow user list
  def follow(other_user)
    target_user << other_user if self != other_user
  end

  # function
  #   ・function to unfollow
  # used
  #    。update follow user list
  def unfollow(other_user)
    target_user.delete(other_user) if following?(other_user)
  end

  # function
  #   ・function to check to follow
  # used
  #    。follow button text
  def following?(other_user)
    target_user.include?(other_user)
  end

  # function
  #   ・function to regist favorite
  # used
  #   ・favorite button
  def favorite(post)
    favorite_post << post if !favorites?(post)
  end

  # function
  #   ・function to unregist favorite
  # used
  #    favorite button
  def unfavorite(post)
    favorite_post.delete(post) if favorites?(post)
  end

  # function
  #   ・function to check to regist favorite
  # used
  #   ・favorite button
  def favorites?(post)
    favorite_post.include?(post)
  end

  private
    # function
    #   ・function to change email address
    # used
    #   ・make it easy to check email
    def downcase_email
      self.email.downcase!
    end

    # function
    #   ・function to digest
    # used
    #   ・make it be secured
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # function
    #   ・function to create token
    # used
    #   ・save login information in cookie
    #   ・save activation token
    def create_token
      SecureRandom.urlsafe_base64
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_logged_in, only:[:edit, :update, :destroy]
  before_action -> {check_correct_user(User)}, only:[:edit, :update, :destroy]

  # function
  #   ・describe user page
  # used
  #   ・want to describe user page
  #     ・redirect when logged in.
  #       etc...
  def show
    @user = User.find_by(id: params[:id])
    @list = @user.post.all
    @list_type = "post"
  end

  # function
  #   ・describe sign up form
  # used
  #   ・want to describe sign up form
  def new
    @user = User.new
    if has_create_user_info?
      get_create_user_info
    end
  end

  # function
  #   ・sign up operation
  # used
  #   ・create user
  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.account_activation(@user).deliver_now
      flash[:success] = "ユーザーの仮登録が完了しました。\nメールを確認して、登録を完了させてください。"
      #   save in session
      redirect_to root_path
    else
      set_create_user_info
      set_error_info(@user)
      redirect_to new_user_path
    end
  end

  # function
  #   ・describe user edit form
  # used
  #   ・update user information
  def edit
    @user = User.find_by(id: params[:id])
    if has_create_user_info?
      get_create_user_info
    end
  end

  # function
  #   ・update operation
  # used
  #   ・update user information
  def update
    @user = User.find_by(id: params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "更新が成功しました。"
      redirect_to @user
    else
      set_error_info(@user)
      redirect_to edit_user_path(@user)
    end
  end

  # function
  #   ・delete operation
  # used
  #   delete user information
  def destroy
    user = current_user
    if logged_in?
      log_out
    end
    user.destroy
    flash[:success] = "ユーザーを削除しました。"
    redirect_to root_path
  end

  def following
    @user = User.find_by(id: params[:id])
    @list = @user.target_user
    @list_type = "follow"
    render :show
  end

  def followers
    @user = User.find_by(id: params[:id])
    @list = @user.following_user
    @list_type = "follow"
    render :show
  end

  private
    # function
    #   ・function to limit post parameter 
    # used
    #   ・prevent malicious request
    def user_params
      params.require(:user).permit(:name, :email, :image_key, :password, :password_confirmation)
    end

    # function
    #   ・function to save input parameter
    # used
    #   ・redirect sign up form when failed to validate
    def set_create_user_info
      if @user.name
        session[:user_name] = @user.name
      end
      if @user.email
        session[:user_email] = @user.email
      end
    end
    
    # function
    #   ・function to get input parameter
    # used
    #   ・redirect sign up form when failed to validate
    def get_create_user_info
      if session[:user_name]
        @user.name = session[:user_name]
        session.delete(:user_name)
      end
      if session[:user_email]
        @user.email = session[:user_email]
        session.delete(:user_email)
      end
    end

    # function
    #   ・function to judge input parameter
    # used
    #   ・redirect sign up form when failed to validate
    def has_create_user_info?
      !(session[:user_name].nil? && session[:user_email].nil?)
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow_list.html.slim
section 
  - @list.each do |l|
      .row.justify-content-center.mx-0
        .border.border-secondary.rounded#follow_list
          .row.my-2.mx-0
            aside.col-4
              section
                - if l.image_key.model['image_key'].nil?
                  - image_tag = ENV['AWS_USER_NO_IMAGE']
                - else
                  - image_tag = l.image_key.to_s
                = image_tag image_tag, alt: "#{l.name}の画像", \
                        title: "#{l.name}", class: "img-thumbnail", id: "person-thumbnail_mini"
            
            aside.col-8.mx-0
              section.my-0.text-left
                .row
                  .col-8.col-md-6
                    = link_to l.name, user_path(l)
                  .col-3.col-md-5
                    = render "follows/follow_button", user: l
                  .col-1.col-md-1
              section.my-0.text-left
                .row
                  div[class="mr-1", id="user_#{l.id}_followings"] = "#{l.target_user.count} followings"
                  div[class="ml-1", id="user_#{l.id}_followers"] = "#{l.following_user.count} followers"
  - if @list.length < 5
    - (15 - (3 *@list.length)).times do
      br
  br

app/views/users/_form.html.slim
.row.justify-content-center.mx-0
  = form_for( @user) do |f| 
    = render 'shared/error_messages'
    table
      tr
        td = f.label :name, "名前："
        td = f.text_field :name, class: 'form-control'
      tr
        td = f.label :email, "メールアドレス："
        td = f.email_field :email, class: 'form-control'
      tr
        td = f.label :image_key, "画像ファイル："
        td = f.file_field :image_key, accept: 'image/jpg,image/jpeg,image/png,image/gif'
      tr
        td = f.label :password, "パスワード："
        td = f.password_field :password, class: 'form-control'
      tr
        td = f.label :password_confirmation, "パスワード（確認）"
        td = f.password_field :password_confirmation, class: 'form-control'
      tr
        td
        td = f.submit yield(:button_text), class: 'btn btn-outline-primary btn-sm', \
                id: 'commit_button'

app/views/users/_post_list.html.slim
section 
  - if @list.length < 1
    - 15.times do
      br
  - else
    - @list.each do |p|
      .row.justify-content-center.mx-0
        .border.rounded-lg.mx-4.mb-4#thumbnail-mini
          h3.text-center.m-1
            = link_to p.title,  post_path(p), class: ""
          - if p.image_key.model['image_key'].nil?
            - image_tag = ENV['AWS_POST_NO_IMAGE']
          - else
            - image_tag = p.image_key.to_s
          = image_tag image_tag, alt: "#{p.title}の画像", title: "#{p.title}", class: "img-thumbnail" 
          .star.row.justify-content-center.m-1
            - 5.times do |s|
              - if p.evaluation >= (s+1)
                .star_on ★
              - else
                .star_off ★
            = "（お気に入り#{p.favorite_user.count}件）"

app/views/users/_profile.html.slim
.row.justify-content-center
  section
    - if @user.image_key.model['image_key'].nil?
      - image_tag = ENV['AWS_USER_NO_IMAGE']
    - else
      - image_tag = @user.image_key.to_s
    = image_tag image_tag, alt: "#{@user.name}の画像", \
            title: "#{@user.name}", class: "img-thumbnail", id: "person-thumbnail"
.row.justify-content-center
  section
    = link_to "#{@user.target_user.count} followings", following_user_path(@user), class: "mx-1", id: "user_#{@user.id}_followings"
    = link_to "#{@user.following_user.count} followers", followers_user_path(@user), class: "mx-1", id: "user_#{@user.id}_followers"
br
.row.justify-content-center
  table
    tr
      td ユーザー名：
      td = @user.name
    tr
      td メールアドレス：
      td = @user.email
br
- if current_user == @user
  .row.justify-content-center
    = link_to "アカウント情報を編集する", edit_user_path(current_user), class: "btn btn-outline-primary btn-sm", id: "edit_user_link"
  br
  .row.justify-content-center
    = link_to "アカウントを削除する", user_path(current_user), method: :delete, class: "btn btn-outline-primary btn-sm",
                id: "delete_user_link", data: { confirm: "アカウントを削除してもよろしいですか？?" }
.row.justify-content-center
  = render "follows/follow_button", user: @user

app/views/users/edit.html.slim
- provide(:button_text, '変更を保存する')

.container-fluid
  .row.justify-content-center.mx-0
    h3 アカウント情報の変更
  br
  .row.justify-content-center
    section
      - if !@user.image_key.model['image_key'].nil?
        - image_tag = @user.image_key.to_s
        = image_tag image_tag, alt: "#{@user.name}の画像", \
              title: "#{@user.name}", class: "img-thumbnail", id: "person-thumbnail"
  = render  "users/form" 

app/views/users/new.html.slim
- provide(:button_text, 'アカウントを作成する')

.container-fluid
  .row.justify-content-center.mx-0
    h3 アカウントの作成
  br
  = render  "users/form" 
  br 
  .row.justify-content-center.mx-0
    = link_to  "ログインはこちら", login_path

app/views/users/show.html.slim
.container-fluid
  .row.justify-content-center.mx-0
    .position-fixed#position-fixed.bg-white
      h3 アカウント情報
  br
  br
  br
  .row.justify-content-center.mx-0
    aside.col-12.d-md-none
      = render 'users/profile'
      br
      br
    aside.col-md-4.d-none.d-md-block
      .position-fixed
        = render 'users/profile'
    aside.col-md-2
    aside.col-md-6
      - if @list_type == 'post'
        = render 'users/post_list'
      - else
        = render 'users/follow_list'
      