config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/about', to: 'static_pages#about'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts
  resources :follows, only: [:create, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  resources :account_activations, only: [:edit]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :prefecture
  has_many :favorite
  has_many :favorite_user, through: :favorite, source: :user
  default_scope -> { order(created_at: :desc) }

  validates :user_id, presence: true
  validates :title, presence: true, length: {maximum: 30}
  validates :prefecture_id, presence: true
  validates :evaluation, presence: true
  validates :content, presence: true, length: {maximum: 1000}

  mount_uploader :image_key, ImageUploader
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_logged_in, only:[:new, :create, :edit, :update, :destroy]
  before_action -> {check_correct_user(Post)}, only:[:edit, :update, :destroy]

  def index
    @post = filltering_post
    @prefecture = {' - ': nil}
    Prefecture.all.each {|p| @prefecture[p.name]=p.id}
  end

  def show
    @post = Post.joins(:user).joins(:prefecture).\
    select("posts.*, users.name as user_name, prefectures.name as prefecture_name").find_by(id: params[:id])
  end

  def new
    @post = Post.new
    @prefecture = Hash.new
    Prefecture.all.each {|p| @prefecture[p.name]=p.id}
    @evaluation = [1, 2, 3, 4, 5]
    if has_create_post_info?
      get_create_post_info
    end
  end

  def create
    user = current_user
    prefecture = Prefecture.find_by(id: prefecture_params)
    @post = user.post.new(post_params)
    @post.prefecture = prefecture
    if @post.save
      flash[:success] = '投稿に成功しました。'
      redirect_to @post
    else
      set_create_post_info
      set_error_info(@post)
      redirect_to new_post_path
    end
  end

  def edit
    @post = Post.find_by(id: params[:id])
    @prefecture = Hash.new()
    Prefecture.all.each {|p| @prefecture[p.name]=p.id}
    @evaluation = [1, 2, 3, 4, 5]
  end

  def update
    @post = Post.find_by(id: params[:id])
    if !(@post.prefecture.id == prefecture_params)
      prefecture = Prefecture.find_by(id: prefecture_params)
      @post.prefecture = prefecture
    end
    if @post.update_attributes(post_params)
      flash[:success] = '更新に成功しました。'
      redirect_to @post
    else
      set_error_info(@post)
      @post = Post.find_by(id: params[:id])
      redirect_to edit_post_path(id: @post.id)
    end


  end

  def destroy
    Post.find_by(id: params[:id]).destroy
    flash[:success] = "削除に成功しました。"
    redirect_to root_url
  end

  private
    def post_params
      params.require(:post).permit(\
        :title, :image_key, :evaluation, :content)
    end

    def prefecture_params
      params[:post][:prefecture]
    end

    # function
    #   ・function to save input parameter
    # used
    #   ・redirect sign up form when failed to validate
    def set_create_post_info
      if @post.title
        session[:post_title] = @post.title
      end
      if @post.prefecture
        session[:post_prefecture_id] = @post.prefecture.id
      end
      if @post.evaluation
        session[:post_evaluation] = @post.evaluation
      end
      if @post.content
        session[:post_content] = @post.content
      end
    end
    
    # function
    #   ・function to get input parameter
    # used
    #   ・redirect sign up form when failed to validate
    def get_create_post_info
      if session[:post_title]
        @post.title = session[:post_title]
        session.delete(:post_title)
      end
      if session[:post_prefecture]
        @post.prefecture = Prefecture.find_by(id: session[:post_prefecture_id])
        session.delete(:post_prefecture)
      end
      if session[:post_evaluation]
        @post.evaluation = session[:post_evaluation]
        session.delete(:post_evaluation)
      end
      if session[:post_content]
        @post.content = session[:post_content]
        session.delete(:post_content)
      end
    end

    # function
    #   ・function to judge input parameter
    # used
    #   ・redirect sign up form when failed to validate
    def has_create_post_info?
      !(session[:post_title].nil? && session[:post_prefecture].nil? && \
        session[:post_evaluation] && session[:post_content])
    end

    # function
    #   ・function to select post
    # used
    #   ・filltering queryset
    def filltering_post
      post = Post.all
      if !params[:word].nil? && params[:word].length > 0
        post = post.where("title LIKE ?", "%#{params[:word]}%")
      end
      if !params[:prefecture].nil? && params[:prefecture].to_i > 0
        post = post.where(prefecture_id: params[:prefecture])
      end
      if !params[:follow].nil? && params[:follow].to_i > 0
        post = post.where(user_id: current_user.target_user.ids)
      end
      post = post.paginate(page: params[:page], per_page: 10)
    end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.slim
.row.justify-content-center
  = form_for(@post) do |f| 
    = render 'shared/error_messages'
    table
      tr
        td = f.label :title, "商品名："
        td = f.text_field :title, class: 'form-control'
      tr
        td = f.label :image_key, "画像ファイル："
        td = f.file_field :image_key, accept: 'image/jpg,image/jpeg,image/png,image/gif'
      tr
        td = f.label :prefecture, "都道府県："
        td = f.select :prefecture, options_for_select(@prefecture, 1), class: 'form-control'
      tr
        td = f.label :evaluation, "評価："
        td = f.select :evaluation, @evaluation, class: 'form-control'
      tr
        td = f.label :content, "詳細内容："
        td = f.text_area :content, class: 'form-control'
      tr
        td
        td 
          .row.m-0
            = f.submit yield(:commit_button_text), class: 'btn btn-outline-primary btn-sm', \
                id: 'commit_button'
            = link_to yield(:cancel_button_text), yield(:cancel_link), class: 'btn btn-outline-primary btn-sm ml-5', \
                id: 'cancel_button', data: {confirm: "保存せずに移動しますか？"}

app/views/posts/_post_list.html.slim
.container-fluid
  - post.each do |p|
    .row.justify-content-center.mx-0
      .border.rounded-lg.m-4#thumbnail
        h3.text-center.m-1
          = link_to p.title,  post_path(p), class: ""
        - if p.image_key.model['image_key'].nil?
          - image_tag = ENV['AWS_POST_NO_IMAGE']
        - else
          - image_tag = p.image_key.to_s
        = image_tag  image_tag, alt: "#{p.title}の画像", title: "#{p.title}", class: "img-thumbnail" 
        .star.row.justify-content-center.m-1
          - 5.times do |s|
            - if p.evaluation >= (s+1)
              .star_on ★
            - else
              .star_off ★
          = "（お気に入り#{p.favorite_user.count}件）"
    br
  .row.justify-content-center
    = will_paginate post, :previous_label => ' &lt 前へ ', :next_label => ' 次へ &gt '

app/views/posts/_search_form.html.slim
.container-fluid
  .row.justify-content-center
    = form_tag(posts_path, method: :get) do |f|
      table
        tr
          td = label_tag :word, '商品名で絞り込み'
          td = text_field_tag :word, params['word']
        tr
          td = label_tag :prefecture, '都道府県名で絞り込み'
          - prefecture = (!params[:prefecture].nil? && params[:prefecture].to_i > 0) ? params['prefecture'] : nil
          td = select_tag :prefecture, options_for_select(@prefecture, prefecture)
        tr
          td = label_tag :follow, 'フォローしているユーザーで絞り込み'
          - if !params[:follow].nil? && params[:follow].to_i > 0
            td = check_box_tag :follow, 1, checked: 'checked'
          - else
            td = check_box_tag :follow
        tr
          td
          td = submit_tag '絞り込み', name: nil
br

app/views/posts/edit.html.slim
- provide(:commit_button_text, '更新する')
- provide(:cancel_button_text, '保存せず戻る')
- provide(:cancel_link, post_path(@post))

.container
  .row.justify-content-center
    h2 お土産の編集
  br
  .row.justify-content-center#thumbnail-mini
    - if !@post.image_key.model['image_key'].nil?
      - image_tag = @post.image_key.to_s
      = image_tag  image_tag, alt: "#{@post.title}の画像", title: "#{@post.title}", class: "img-thumbnail"
  = render  "posts/form" 

app/views/posts/index.html.slim
.container-fluid.jumbotron-fluid.mb-5#about
  .row.justify-content-center.mb-5
    h3.mt-3 みやログについて
  .row.justify-content-center.mb-3
    p 旅行へ行ったときにどんなお土産を買っていこうか迷う。<br>
      よく出張へ行くが毎回同じお土産を買っているため、違うものを探したい。<br>
      そんなあなたのお土産探しの助けになるサービスです。
= render "posts/search_form"
= render "posts/post_list", post: @post

app/views/posts/new.html.slim
- provide(:commit_button_text, '投稿する')
- provide(:cancel_button_text, '保存せず戻る')
- provide(:cancel_link, root_path)

.container
  .row.justify-content-center
    h2 お土産の投稿
  br
  br 
  = render  "posts/form" 

app/views/posts/show.html.slim
.container
  .row.justify-content-center
    h2 = "#{@post.title}(#{@post.prefecture_name})"
  br
  .row.justify-content-end.mr-1
    p 投稿者　：　
    = link_to "#{@post.user_name}", user_path(@post.user)
    = "(#{@post.user.following_user.count}人登録)"
  .row.justify-content-end.mr-1
    = render "follows/follow_button", user: @post.user
  br
  .row.justify-content-end.mr-1
    p = "投稿日時　：　#{@post.created_at.strftime("%Y/%m/%d/ %H:%M")}"
  
  - if @post.user == current_user
    / 編集ボタン
    .row.justify-content-end.mr-1
      = link_to "投稿を編集する",  edit_post_path(@post), class:"btn btn-outline-primary btn-sm", id: "edit_button"
    / 削除ボタン
    .row.justify-content-end.mr-1
      = link_to "投稿を削除する",  post_path(@post), method: :delete,class:"btn btn-outline-primary btn-sm", \
          id: "delete_button", data: {confirm: "投稿を削除しますか？"}
  - else
    br
    br
  
  .row.justify-content-center
    - if @post.image_key.model['image_key'].nil?
      - image_tag = ENV['AWS_POST_NO_IMAGE']
    - else
      - image_tag = @post.image_key.to_s
    = image_tag  image_tag, alt: "#{@post.title}の画像", title: "#{@post.title}", class: "img-thumbnail" 
  .star.row.justify-content-center.m-1
    - 5.times do |s|
      - if @post.evaluation >= (s+1)
        .star_on ★
      - else
        .star_off ★
    = "（お気に入り#{@post.favorite_user.count}件）"
  .row.justify-content-center
    p = @post.content
  br
  / お気に入り追加ボタン
  .row.justify-content-center
    = render "favorites/favorite_button", post: @post
  br
  / おねだりボタン
  .row.justify-content-center
    = link_to "LINEでおねだり", "https://social-plugins.line.me/lineit/share?text=これ買ってきて%21&title#{@post.title}=&url=#{post_url(@post)}", \
      class:"btn btn-success btn-sm", target: :_blank
  br