config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get '/about', to: 'static_pages#about'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :posts
  resources :follows, only: [:create, :destroy]
  resources :favorites, only: [:index, :create, :destroy]
  resources :account_activations, only: [:edit]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/views/layouts/_flash.html.slim
.row.justify-content-center.mx-0
  - flash.each do |message_type, message|
    dov class="alert alert-#{message_type}" = message

app/views/layouts/_footer.html.slim
hr
br
br
br
footer
  .container-fluid
    .row.justify-content-center
      = link_to "トップページへ", root_path
    .row.justify-content-center
      p 
        | COPYRIGHT &#169; みやログ 2019

app/views/layouts/_form_post.html.slim
.row.justify-content-center
  = form_for(@post) do |f| 
    = render 'shared/error_messages'
    table
      tr
        td = f.label :title, "商品名："
        td = f.text_field :title, class: 'form-control'
      tr
        td = f.label :image_key, "画像ファイル："
        td = f.file_field :image_key, accept: 'image/jpg,image/jpeg,image/png,image/gif'
      tr
        td = f.label :prefecture, "都道府県："
        td = f.select :prefecture, @prefecture, class: 'form-control'
      tr
        td = f.label :evaluation, "評価："
        td = f.select :evaluation, @evaluation, class: 'form-control'
      tr
        td = f.label :content, "詳細内容："
        td = f.text_area :content, class: 'form-control'
      tr
        td
        td 
          .row.m-0
            = f.submit yield(:commit_button_text), class: 'btn btn-outline-primary btn-sm', \
                id: 'commit_button'
            = link_to yield(:cancel_button_text), yield(:cancel_link), class: 'btn btn-outline-primary btn-sm ml-5', \
                id: 'cancel_button', data: {confirm: "保存せずに移動しますか？"}

app/views/layouts/_form_user.html.slim
.row.justify-content-center.mx-0
  = form_for( @user) do |f| 
    = render 'shared/error_messages'
    table
      tr
        td = f.label :name
        td = f.text_field :name, class: 'form-control'
      tr
        td = f.label :email
        td = f.email_field :email, class: 'form-control'
      tr
        td = f.label :Password
        td = f.password_field :password, class: 'form-control'
      tr
        td = f.label :password_confirmation, "Password(confirmation)"
        td = f.password_field :password_confirmation, class: 'form-control'
      tr
        td
        td = f.submit yield(:button_text), class: 'btn btn-outline-primary btn-sm', \
                id: 'commit_button'

app/views/layouts/_header.html.slim
header.navbar.fixed-top.navbar-inverse.bg-primary.py-0
  .container-fluid
    h1.text-white#logo = link_to "みやログ", root_path, class: "nav-link text-white"
    nav
      ul.nav.navbar-nav.navbar-right.flex-sm-row.my-2
        li.nav-item.ml-3 = link_to "このサイトについて", about_path, class: "text-white"
        /li.nav-item.ml-3 = link_to "問い合わせ(未実装)", "#", class: "text-white"
        li.nav-item.ml-3.dropdown
          = link_to "#", 'data-toggle'=>"dropdown", class: "dropdown-toggle text-white"
            | アカウントサービス
          ul.dropdown-menu.bg-info.border-white.position-absolute#dropdown
            - if logged_in?
              li.dropdown-items.mx-1 = link_to "プロフィール", user_path(current_user), class: "text-white"
              li.dropdown-items.mx-1 = link_to "新規投稿", new_post_path, class: "text-white"
              li.dropdown-items.mx-1 = link_to "お気に入り投稿リスト", favorites_path, class: "text-white"
              li.dropdown-items.mx-1 = link_to "ログアウト", logout_path, method: :delete, class: "text-white"
            - else
              li.dropdown-items.mx-1 = link_to "アカウント作成", new_user_path, class: "text-white"
              li.dropdown-items.mx-1 = link_to "ログイン", login_path, class: "text-white"

app/views/layouts/_shim.html.slim
/ [if lt IE 9]
script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | みやログ
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = render 'layouts/shim'
  body
    .container-fluid
      = render 'layouts/header'
      = render 'layouts/flash'
      = yield
      / TODO : alert message
      = render 'layouts/footer'
      / TODO : debug message
      = debug(params) if Rails.env.development?